### ISSUE TITLE
v1.5 breaks tests, and/or rubocop

### ISSUE THREAD

**Issue by bmulholland** [test-prof/test-prof#331]
When I upgrade to v1.5, all my tests start failing:
```
> be rspec
     Failure/Error: raise Plugin::LoadError, plugin_name

     RuboCop::Plugin::LoadError:
       Failed to load plugin `test-prof` because the corresponding plugin class could not be determined for instantiation.
       Try upgrading it first (e.g., `bundle update test-prof`).
       If `test-prof` is not yet a plugin, use `require: test-prof` instead of `plugins: test-prof` in your configuration.

       For further assistance, check with the developer regarding the following points:
       https://docs.rubocop.org/rubocop/plugin_migration_guide.html
```

And okay, the cops seem like a good idea, so let's set that up... add test_prof/rubocop to rubocop plugins, and:

```
> be rubocop
Error: Failed to load plugin `test_prof/rubocop` because the corresponding plugin class could not be determined for instantiation.
Try upgrading it first (e.g., `bundle update test_prof/rubocop`).
If `test_prof/rubocop` is not yet a plugin, use `require: test_prof/rubocop` instead of `plugins: test_prof/rubocop` in your configuration.

For further assistance, check with the developer regarding the following points:
https://docs.rubocop.org/rubocop/plugin_migration_guide.html
```

**Comment by bmulholland** [comment]
Oh, the rubocop changes are in the changelog as v1.4.5, which wasn't even published to rubygems, and which has no Github tag/release either...

**Comment by geoffharcourt** [comment]
We're seeing something similar. Here's a slightly longer trace (I'm working on getting a longer one):

```

23) Search::ContentSearch#results_count caching behavior when two requests are made with the same checkbox filters performs just one hybrid search
--
Failure/Error: raise Plugin::LoadError, plugin_name
 
RuboCop::Plugin::LoadError:
Failed to load plugin `test-prof` because the corresponding plugin class could not be determined for instantiation.
Try upgrading it first (e.g., `bundle update test-prof`).
If `test-prof` is not yet a plugin, use `require: test-prof` instead of `plugins: test-prof` in your configuration.
 
For further assistance, check with the developer regarding the following points:
https://docs.rubocop.org/rubocop/plugin_migration_guide.html
# /bundle/ruby/3.4.0/gems/rubocop-1.81.7/lib/rubocop/plugin/loader.rb:95:in 'RuboCop::Plugin::Loader.constantize_plugin_from_gemspec_metadata'
# /bundle/ruby/3.4.0/gems/rubocop-1.81.7/lib/rubocop/plugin/loader.rb:82:in 'RuboCop::Plugin::Loader.constantize'
# /bundle/ruby/3.4.0/gems/rubocop-1.81.7/lib/rubocop/plugin/loader.rb:63:in 'RuboCop::Plugin::Loader.constantize_plugin_from'
# /bundle/ruby/3.4.0/gems/rubocop-1.81.7/lib/rubocop/plugin/loader.rb:25:in 'block in RuboCop::Plugin::Loader.load'
# /bundle/ruby/3.4.0/gems/rubocop-1.81.7/lib/rubocop/plugin/loader.rb:22:in 'Hash#each'
# /bundle/ruby/3.4.0/gems/rubocop-1.81.7/lib/rubocop/plugin/loader.rb:22:in 'Enumerable#filter_map'
# /bundle/ruby/3.4.0/gems/rubocop-1.81.7/lib/rubocop/plugin/loader.rb:22:in 'RuboCop::Plugin::Loader.load'
# /bundle/ruby/3.4.0/gems/rubocop-1.81.7/lib/rubocop/plugin.rb:38:in 'RuboCop::Plugin.integrate_plugins'
# /bundle/ruby/3.4.0/gems/rubocop-1.81.7/lib/rubocop/rspec/cop_helper.rb:25:in 'block in <module:CopHelper>'
# ------------------
# --- Caused by: ---
# NameError:
#   uninitialized constant RuboCop::TestProf
#   /bundle/ruby/3.4.0/gems/rubocop-1.81.7/lib/rubocop/plugin/loader.rb:93:in 'Module#const_get'
```

**Comment by palkan** [comment]
Thanks for the report!

I've pushed a fix to master, could you please give it a try? @bmulholland @geoffharcourt

**Comment by bmulholland** [comment]
I really thought I tried `test-prof` in rubocop.yml, but trying again that does work. It's just that rspec suggests it's not right:

rspec does still fail, with a similar backtrace to the above (included below), which isn't very helpful (and why I didn't include the full thing originally). Adding the woraround require that @timdiggins suggests does fix it. As with Tim, we have tests for custom RuboCop rules, and that'll be what's loading RuboCop during tests.

```
  2100) Messaging::FrontendUsageFormatter.format_error_message formats message for missing error message
        Failure/Error: raise Plugin::LoadError, plugin_name

        RuboCop::Plugin::LoadError:
          Failed to load plugin `test-prof` because the corresponding plugin class could not be determined for instantiation.
          Try upgrading it first (e.g., `bundle update test-prof`).
          If `test-prof` is not yet a plugin, use `require: test-prof` instead of `plugins: test-prof` in your configuration.

          For further assistance, check with the developer regarding the following points:
          https://docs.rubocop.org/rubocop/plugin_migration_guide.html
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rubocop-1.81.7/lib/rubocop/plugin/loader.rb:95:in 'RuboCop::Plugin::Loader.constantize_plugin_from_gemspec_metadata'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rubocop-1.81.7/lib/rubocop/plugin/loader.rb:82:in 'RuboCop::Plugin::Loader.constantize'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rubocop-1.81.7/lib/rubocop/plugin/loader.rb:63:in 'RuboCop::Plugin::Loader.constantize_plugin_from'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rubocop-1.81.7/lib/rubocop/plugin/loader.rb:25:in 'block in RuboCop::Plugin::Loader.load'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rubocop-1.81.7/lib/rubocop/plugin/loader.rb:22:in 'Hash#each'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rubocop-1.81.7/lib/rubocop/plugin/loader.rb:22:in 'Enumerable#filter_map'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rubocop-1.81.7/lib/rubocop/plugin/loader.rb:22:in 'RuboCop::Plugin::Loader.load'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rubocop-1.81.7/lib/rubocop/plugin.rb:38:in 'RuboCop::Plugin.integrate_plugins'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rubocop-1.81.7/lib/rubocop/rspec/cop_helper.rb:25:in 'block in <module:CopHelper>'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/hooks.rb:365:in 'BasicObject#instance_exec'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/hooks.rb:365:in 'RSpec::Core::Hooks::BeforeHook#run'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/hooks.rb:529:in 'block in RSpec::Core::Hooks::HookCollections#run_owned_hooks_for'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/hooks.rb:528:in 'Array#each'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/hooks.rb:528:in 'RSpec::Core::Hooks::HookCollections#run_owned_hooks_for'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/hooks.rb:480:in 'RSpec::Core::Hooks::HookCollections#run'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/example_group.rb:560:in 'block in RSpec::Core::ExampleGroup.run_before_context_hooks'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/memoized_helpers.rb:208:in 'block in RSpec::Core::MemoizedHelpers::ContextHookMemoized.isolate_for_context_hook'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/memoized_helpers.rb:204:in 'BasicObject#instance_exec'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/memoized_helpers.rb:204:in 'RSpec::Core::MemoizedHelpers::ContextHookMemoized.isolate_for_context_hook'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/example_group.rb:559:in 'RSpec::Core::ExampleGroup.run_before_context_hooks'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/example_group.rb:613:in 'RSpec::Core::ExampleGroup.run'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/runner.rb:121:in 'block (3 levels) in RSpec::Core::Runner#run_specs'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/runner.rb:121:in 'Array#map'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/runner.rb:121:in 'block (2 levels) in RSpec::Core::Runner#run_specs'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/configuration.rb:2097:in 'RSpec::Core::Configuration#with_suite_hooks'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/runner.rb:116:in 'block in RSpec::Core::Runner#run_specs'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/reporter.rb:74:in 'RSpec::Core::Reporter#report'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/runner.rb:115:in 'RSpec::Core::Runner#run_specs'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/runner.rb:89:in 'RSpec::Core::Runner#run'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/runner.rb:71:in 'RSpec::Core::Runner.run'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/lib/rspec/core/runner.rb:45:in 'RSpec::Core::Runner.invoke'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rspec-core-3.13.6/exe/rspec:4:in '<top (required)>'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/bin/rspec:25:in 'Kernel#load'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/bin/rspec:25:in '<top (required)>'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/bundler-4.0.0/lib/bundler/cli/exec.rb:61:in 'Kernel.load'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/bundler-4.0.0/lib/bundler/cli/exec.rb:61:in 'Bundler::CLI::Exec#kernel_load'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/bundler-4.0.0/lib/bundler/cli/exec.rb:24:in 'Bundler::CLI::Exec#run'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/bundler-4.0.0/lib/bundler/cli.rb:494:in 'Bundler::CLI#exec'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/bundler-4.0.0/lib/bundler/vendor/thor/lib/thor/command.rb:28:in 'Bundler::Thor::Command#run'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/bundler-4.0.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'Bundler::Thor::Invocation#invoke_command'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/bundler-4.0.0/lib/bundler/vendor/thor/lib/thor.rb:538:in 'Bundler::Thor.dispatch'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/bundler-4.0.0/lib/bundler/cli.rb:35:in 'Bundler::CLI.dispatch'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/bundler-4.0.0/lib/bundler/vendor/thor/lib/thor/base.rb:584:in 'Bundler::Thor::Base::ClassMethods#start'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/bundler-4.0.0/lib/bundler/cli.rb:29:in 'Bundler::CLI.start'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/bundler-4.0.0/exe/bundle:28:in 'block in <top (required)>'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/bundler-4.0.0/lib/bundler/friendly_errors.rb:118:in 'Bundler.with_friendly_errors'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/bundler-4.0.0/exe/bundle:20:in '<top (required)>'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/bin/bundle:25:in 'Kernel#load'
        # /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/bin/bundle:25:in '<main>'
        #
        #   Showing full backtrace because every line was filtered out.
        #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
        #   RSpec::Configuration#backtrace_inclusion_patterns for more information.
        # ------------------
        # --- Caused by: ---
        # NameError:
        #   uninitialized constant RuboCop::TestProf
        #   /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/rubocop-1.81.7/lib/rubocop/plugin/loader.rb:93:in 'Module#const_get'
```

**Comment by viralpraxis** [comment]
@geoffharcourt 

Could you please confirm whether your `Gemfile` looks like this (with the groups in this specific order)?

```ruby
group :test do
  gem "test-prof"
end

group :lint, :test do
  gem "rubocop"
end
```

If that's the case, does changing the order of these groups helps?

**Comment by viralpraxis** [comment]
I think there's already a patch https://github.com/jamiecobbett/test-prof/commit/162207f746812a5115b8d7c2636a4ed4cc58bab2 -- autoloading should not be conditional

With the patch I don't see any issues with `rubocop` or `rspec` in all the combinations of gem ordering

**Comment by geoffharcourt** [comment]
@viralpraxis we do have custom cops! What's odd is that this issue happens only with 1.5.x and appears to be somewhat random in terms of what specs it breaks (the same specs that fail in CI pass locally when run in isolation, etc.)

I'm experimenting with the Gemfile ordering to see if that has any impact, thanks for the suggestion.

**Comment by viralpraxis** [comment]
I've opened https://github.com/test-prof/test-prof/pull/334 to check if it resolves the issue.
